### ISSUE TITLE
support for https communtion with the server

### ISSUE THREAD

**Issue by aldinp16** [maxmunzel/kvass#8]
I try to run `kvass serve` behind Nginx reverse proxy using HTTPS. but get the error `2022/08/05 10:07:00: Couldn't get updates from server.  cipher: message authentication failed`. This error is because kvass forces push and pull communication using HTTP. any suggestion on how I run kvass behind Nginx reverse proxy with HTTPS? for now, I am bypassing `kvass config remote` command to allow http/https in my fork [@aldinp16/kvass](https://github.com/aldinp16/kvass).

**Comment by maxmunzel** [comment]
Hi Aldin!

Thanks for bringing this up. HTTPS (at least for the file-sharing) is definitely on the TODO-List and your fork looks like
a good improvement on the current state.

I would suggest you to add a check, so that the current form of omitting the `http://` still works and opening a PR.

Something like this: 

```golang
if !regex.matches("\\w+://.*", hostname) {
    hostname = "http://" + hostname
}
```

What do you think?

**Comment by aldinp16** [comment]
Thanks for the feedback. sound good to me, we can use `ParseRequestURI()` from `net/uri` for parse & validation the hostname. I will try the fix and make a pull request

**Comment by maxmunzel** [comment]
Thanks for your contribution!
